In [36]:
import pandas as pd
import numpy as np

In [37]:
df = pd.read_csv('tips.csv')
df.head()

,total_bill,tip,gender,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3.560330e+15,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4.478070e+15,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6.011810e+15,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4.676140e+15,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4.832730e+15,Sun2251

In [38]:
df['tip_percentage'] = (100 * df['tip']/df['total_bill']).round(2)

In [39]:
df['price_per_person'] = (df['total_bill']/df['size']).round(2)

In [41]:
df[['total_bill', 'tip', 'size', 'tip_percentage', 'price_per_person']].head()

   total_bill   tip  size  tip_percentage  price_per_person
0       16.99  1.01     2            5.94              8.49
1       10.34  1.66     3           16.05              3.45
2       21.01  3.50     3           16.66              7.00
3       23.68  3.31     2           13.98             11.84
4       24.59  3.61     4           14.68              6.15

In [42]:
# Condition Column Creation

In [46]:
df['big_tipper'] = np.where(df['tip_percentage'] > 20 ,'Yes','No')

In [47]:
# Several Outcomes : np.select(conditions,choices,default)

In [48]:
df['bill_category'] = np.select([df['total_bill'] < 10 , df['total_bill'] <30],['$','$$'],default='$$$')

In [51]:
df[['total_bill','bill_category']]

     total_bill bill_category
0         16.99            $$
1         10.34            $$
2         21.01            $$
3         23.68            $$
4         24.59            $$
..          ...           ...
239       29.03            $$
240       27.18            $$
241       22.67            $$
242       17.82            $$
243       18.78            $$

[244 rows x 2 columns]

In [52]:
# rename and drop column

In [53]:
df = df.rename(columns={'total_bill':'bill','Payer Name':'payer_name'})

In [54]:
df = df.drop(columns = ['CC Number', 'Payment ID'])

In [55]:
# data type conversion

In [56]:
df['size'] = df['size'].astype(float)  #int->float

In [57]:
df['day'] = df['day'].astype('category')
print(df.dtypes)

bill                 float64
tip                  float64
gender                   str
smoker                   str
day                 category
time                     str
size                 float64
price_per_person     float64
payer_name               str
tip_percentage       float64
big_tipper               str
bill_category            str
dtype: object