In [1]:
import pandas as pd

In [5]:
df = pd.read_csv('tips.csv')
df.head()

,total_bill,tip,gender,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3.560330e+15,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4.478070e+15,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6.011810e+15,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4.676140e+15,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4.832730e+15,Sun2251

In [6]:
len(df)

244

In [7]:
df.columns.tolist()

['total_bill',
 'tip',
 'gender',
 'smoker',
 'day',
 'time',
 'size',
 'price_per_person',
 'Payer Name',
 'CC Number',
 'Payment ID']

In [8]:
df.describe()

       total_bill         tip        size  price_per_person     CC Number
count  244.000000  244.000000  244.000000        244.000000  2.440000e+02
mean    19.785943    2.998279    2.569672          7.888197  2.563495e+15
std      8.902412    1.383638    0.951100          2.914234  2.369340e+15
min      3.070000    1.000000    1.000000          2.880000  6.040679e+10
25%     13.347500    2.000000    2.000000          5.800000  3.040732e+13
50%     17.795000    2.900000    2.000000          7.255000  3.525320e+15
75%     24.127500    3.562500    3.000000          9.390000  4.553675e+15
max     50.810000   10.000000    6.000000         20.270000  6.596450e+15

In [9]:
df['day'].unique()

<StringArray>
['Sun', 'Sat', 'Thur', 'Fri']
Length: 4, dtype: str

In [10]:
df['day'].value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [11]:
df.isnull().sum()

total_bill          0
tip                 0
gender              0
smoker              0
day                 0
time                0
size                0
price_per_person    0
Payer Name          0
CC Number           0
Payment ID          0
dtype: int64

In [12]:
df.duplicated().sum()

np.int64(0)

In [15]:
summary = df.groupby('day')['tip'].mean().round(2)
summary

day
Fri     2.73
Sat     2.99
Sun     3.26
Thur    2.77
Name: tip, dtype: float64

In [16]:
summary.to_csv('tips_average_by_day.csv')

In [19]:
print(df['total_bill'])

0      16.99
1      10.34
2      21.01
3      23.68
4      24.59
       ...
239    29.03
240    27.18
241    22.67
242    17.82
243    18.78
Name: total_bill, Length: 244, dtype: float64

In [20]:
print(type(df['total_bill']))

<class 'pandas.Series'>

In [21]:
print(df[['total_bill','tip']])

     total_bill   tip
0         16.99  1.01
1         10.34  1.66
2         21.01  3.50
3         23.68  3.31
4         24.59  3.61
..          ...   ...
239       29.03  5.92
240       27.18  2.00
241       22.67  2.00
242       17.82  1.75
243       18.78  3.00

[244 rows x 2 columns]

In [22]:
print(df.tip.head())

0    1.01
1    1.66
2    3.50
3    3.31
4    3.61
Name: tip, dtype: float64

In [23]:
# Min-Max

In [24]:
print('Highest bill :',df['total_bill'].max())

Highest bill : 50.81

In [25]:
print(df.loc[df['total_bill'].idxmax()])

total_bill                       50.81
tip                               10.0
gender                            Male
smoker                             Yes
day                                Sat
time                            Dinner
size                                 3
price_per_person                 16.94
Payer Name               Gregory Clark
CC Number           5473850000000000.0
Payment ID                     Sat1954
Name: 170, dtype: object

In [26]:
print(df.loc[df['total_bill'].idxmin()])

total_bill                        3.07
tip                                1.0
gender                          Female
smoker                             Yes
day                                Sat
time                            Dinner
size                                 1
price_per_person                  3.07
Payer Name               Tiffany Brock
CC Number           4359490000000000.0
Payment ID                     Sat3455
Name: 67, dtype: object

In [27]:
#Update

In [28]:
df.loc[0,'tip'] = 1.50  # one row 0th

In [32]:
df.loc[0]

total_bill                       16.99
tip                                1.5
gender                          Female
smoker                              No
day                                Sun
time                            Dinner
size                                 2
price_per_person                  8.49
Payer Name          Christy Cunningham
CC Number           3560330000000000.0
Payment ID                     Sun2959
Name: 0, dtype: object

In [29]:
df.loc[df['size'] >= 5 , 'time'] = 'Dinner'  # all rows matching a condition

In [31]:
df.loc[df['size'] >= 5]

,total_bill,tip,gender,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
125,29.80,4.20,Female,No,Thur,Dinner,6,4.97,Angela Sanchez,5.038570e+11,Thur3948
141,34.30,6.70,Male,No,Thur,Dinner,6,5.72,Steven Carlson,3.526520e+15,Thur1025
142,41.19,5.00,Male,No,Thur,Dinner,5,8.24,Eric Andrews,4.356530e+15,Thur3621
143,27.05,5.00,Female,No,Thur,Dinner,6,4.51,Regina Jones,4.311050e+12,Thur6179
155,29.85,5.14,Female,No,Sun,Dinner,5,5.97,Madison Wilson,4.210880e+15,Sun9176
156,48.17,5.00,Male,No,Sun,Dinner,6,8.03,Ryan Gonzales,3.523150e+15,Sun7518
185,20.69,5.00,Male,No,Sun,Dinner,5,4.14,Joseph Howell,3.036240e+13,Sun5842
187,30.46,2.00,Male,Yes,Sun,Dinner,5,6.09,David Barrett,4.792880e+15,Sun9987
216,28.15,3.00,Male,Yes,Sat,Dinner,5,5.63,Shawn Barnett PhD,4.590980e+12,Sat7320