In [1]:
import numpy as np
import pandas as pd

Q1

Write a Pandas program to create and display a one-dimensional array-like
object containing an array of data using Pandas module.

In [2]:
df = pd.Series([1,2,3,4,5])
print(df,df.ndim)

0    1
1    2
2    3
3    4
4    5
dtype: int64 1

Q2

Write a Pandas program to convert a Panda module Series to Python list
and it's type.

In [3]:
df = pd.Series([1,2,3,4,5])
li = list(df)
type(li)

list

Q3

Write a Pandas program to add, subtract, multiple and divide two Pandas Series.
Sample Series: [2, 4, 6, 8, 10], [1, 3, 5, 7, 9]

In [4]:
df1 = pd.Series([2, 4, 6, 8, 10])
df2 = pd.Series([1, 3, 5, 7, 9])

print(df1 + df2)
print(df1 - df2)
print(df1 * df2)
print(df1 / df2)

0     3
1     7
2    11
3    15
4    19
dtype: int64
0    1
1    1
2    1
3    1
4    1
dtype: int64
0     2
1    12
2    30
3    56
4    90
dtype: int64
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64

Q4

Write a Pandas program to compare the elements of the two Pandas Series.
Sample Series: [2, 4, 6, 8, 10], [1, 3, 5, 7, 10]

In [5]:
df1 = pd.Series([2, 4, 6, 8, 10])
df2 = pd.Series([1, 3, 5, 7, 10])

print(df1 == df2)
print(df1.compare(df2))
print(df1.equals(df2))

0    False
1    False
2    False
3    False
4     True
dtype: bool
   self  other
0   2.0    1.0
1   4.0    3.0
2   6.0    5.0
3   8.0    7.0
False

Q5

Write a Pandas program to convert a dictionary to a Pandas series.

In [6]:
dict = {'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800}
df = pd.Series(dict)
df

a    100
b    200
c    300
d    400
e    800
dtype: int64

Q6 

Write a Pandas program to convert a NumPy array to a Pandas series.

In [7]:
arr = np.array([10, 20, 30, 40, 50])
df = pd.Series(arr)
df

0    10
1    20
2    30
3    40
4    50
dtype: int64

Q7

Write a Pandas program to change the data type of given a column or a
Series.

In [8]:
sr = pd.Series([100, 200, 'python', 300.12, 400])
print(sr)
pd.to_numeric(sr, errors = 'coerce')

0       100
1       200
2    python
3    300.12
4       400
dtype: object

0    100.00
1    200.00
2       NaN
3    300.12
4    400.00
dtype: float64

Q8

Write a Pandas program to convert the first column of a DataFrame as a
Series.

In [9]:
df = pd.DataFrame({'col1' : [1,2,3,4,5],
      'col2': [2,3,4,5,6],
      'col3': [4,5,6,7,8]
      })
col1 = pd.Series(df.col1)
col1
# col1 = pd.Series(df['col1'])
# col1

0    1
1    2
2    3
3    4
4    5
Name: col1, dtype: int64

Q9

Write a Pandas program to convert a given Series to an array.

In [10]:
df = pd.Series([100, 200, 'python', 300.12, 400])
arr = np.array(df)
arr

array([100, 200, 'python', 300.12, 400], dtype=object)

Q10

Write a Pandas program to convert Series of lists to one Series.

In [11]:
df1 = pd.Series([['Red', 'Green', 'White'],
               ['Red', 'Black'],
               ['Yellow']]
               )
df = df1.explode().reset_index(drop = True)
df

0       Red
1     Green
2     White
3       Red
4     Black
5    Yellow
dtype: str

Q11

Write a Pandas program to sort a given Series.

In [12]:
df = pd.Series([100, 200, 'python', 300.12, 400])
df = df.sort_values(key =  lambda x : x.astype(str))
df

0       100
1       200
3    300.12
4       400
2    python
dtype: object

Q12

Write a Pandas program to add some data to an existing Series.

In [266]:
df = pd.Series([100, 200, 'python', 300.12, 400])
df = pd.concat([df,pd.Series([500,'php'])],ignore_index = True)
df

0       100
1       200
2    python
3    300.12
4       400
5       500
6       php
dtype: object

Q13

Write a Pandas program to create a subset of a given series based on value and
condition.

In [265]:
df = pd.Series([0,1,2,3,4,5,6,7,8,9,10])
subset = df[df <= 5]
subset

0    0
1    1
2    2
3    3
4    4
5    5
dtype: int64

Q14

Write a Pandas program to change the order of index of a given series.

In [36]:
df = pd.Series([1,2,3,4,5],index = ['A','B','C','D','E'])
new_index = ['B','A','D','C','E']
df = df.reindex(new_index)
df

B    2
A    1
D    4
C    3
E    5
dtype: int64

Q15

Write a Pandas program to create the mean and standard deviation of the data of a
given Series.

In [16]:
df = pd.Series([1,2,5,3,4])
print('Mean:', df.mean())
print('Standard Deviation:', df.std())
df

Mean: 3.0
Standard Deviation: 1.5811388300841898

0    1
1    2
2    5
3    3
4    4
dtype: int64

Q16 

Write a Pandas program to get the items of a given series not present in another given
series.

In [17]:
sr1 = pd.Series([1,2,0,7,8,5,3])
sr2 = pd.Series([5,7,8,6])

sr1[~sr1.isin(sr2)]

0    1
1    2
2    0
6    3
dtype: int64

Q17

Write a Pandas program to get the items which are not common of two given series.

In [126]:
sr1 = pd.Series([1,2,3,4,5])
sr2 = pd.Series([2,4,6,8,10])

# common = pd.Series(np.intersect1d(sr1,sr2))
# total = pd.Series(np.union1d(sr1,sr2))

# total[~total.isin(common)]

df = pd.concat([sr1,sr2],ignore_index = True)
df.drop_duplicates(keep = False)

0     1
2     3
4     5
7     6
8     8
9    10
dtype: int64

Q18

Write a Pandas program to compute the minimum, 25th percentile, median, 75th, and
maximum of a given series.

In [127]:
df = pd.Series([10,12,45,32,21,23,18,90,34])
print("Min :- ",df.min())
print("25th Percentile :-",np.percentile(df,25))
print("Median :-",df.median())
print("25th Percentile :-",np.percentile(df,75))
print("Max :-",df.max())

Min :-  10
25th Percentile :- 18.0
Median :- 23.0
25th Percentile :- 34.0
Max :- 90

Q19

Write a Pandas program to calculate the frequency counts of each unique value of a
given series.

In [22]:
df = pd.Series(np.random.randint(0,9,50))
df.value_counts()

8    10
7     7
3     7
2     6
0     5
4     5
5     4
6     3
1     3
Name: count, dtype: int64

Q20

Write a Pandas program to display most frequent value in a given series and replace
everything else as 'Other' in the series.

In [144]:
df = pd.Series([1,2,3,3,4,6,5,3,2,8,9,0])
most_frequent = df.value_counts().index[0]
df = df.where(df == most_frequent,"Other")
df

0     Other
1     Other
2         3
3         3
4     Other
5     Other
6     Other
7         3
8     Other
9     Other
10    Other
11    Other
dtype: object

Q21

Write a Pandas program to find the positions of numbers that are multiples of 5 of a
given series.

In [24]:
df = pd.Series([5,10,12,24,25,35,50,51])
df.index[df % 5 == 0]

Index([0, 1, 4, 5, 6], dtype='int64')

Q22

Write a Pandas program to extract items at given positions of a given series.

In [25]:
df = pd.Series([5,10,12,24,25,35,50,51])
pos = [0,3,4,5,6]
df.iloc[pos]

0     5
3    24
4    25
5    35
6    50
dtype: int64

Q23

Write a Pandas program to get the positions of items of a given series in another
given series.

In [26]:
df1 = pd.Series([5,10,12,24,25,35,50,51])
df2 = pd.Series([10,35,24,25])
df1.index[df1.isin(df2)].tolist()

[1, 3, 4, 5]

Q24

Write a Pandas program convert the first and last character of each word to upper
case in each word of a given series.

In [27]:
df = pd.Series(['php','python','java','c#'])
df = df.str.title()
df.str[:-1] + df.str[-1].str.upper()

0       PhP
1    PythoN
2      JavA
3        C#
dtype: str

Q25

Write a Pandas program to calculate the number of characters in each word in a given
series.

In [28]:
df = pd.Series(['php','python','java','c#'])
df.str.len()

0    3
1    6
2    4
3    2
dtype: int64

Q26

Write a Pandas program to compute difference of differences between consecutive
numbers of a given series.

In [29]:
df = pd.Series([1,3,5,8,10,11,15])
print(df.diff())
print(df.diff().diff())

0    NaN
1    2.0
2    2.0
3    3.0
4    2.0
5    1.0
6    4.0
dtype: float64
0    NaN
1    NaN
2    0.0
3    1.0
4   -1.0
5   -1.0
6    3.0
dtype: float64

Q27

Write a Pandas program to convert a series of date strings to a timeseries.

In [30]:
df = pd.Series(['01 Jan 2015','10-02-2016','20180307','2014/05/06','2016-04-12','2019-04-06T11:20'])
df = pd.to_datetime(df,format='mixed')
print(df)

0   2015-01-01 00:00:00
1   2016-10-02 00:00:00
2   2018-03-07 00:00:00
3   2014-05-06 00:00:00
4   2016-04-12 00:00:00
5   2019-04-06 11:20:00
dtype: datetime64[us]

Q28

Write a Pandas program to get the day of month, day of year, week number and day
of week from a given series of date strings.

In [257]:
df = pd.Series(['01 Jan 2015','10-02-2016','20180307','2014/05/06','2016-04-12','2019-04-06T11:20'])
df = pd.to_datetime(df,format='mixed')
df.dt.day.tolist(),df.dt.day_of_year.tolist(),df.dt.isocalendar().week.tolist(),df.dt.day_name().tolist()

([1, 2, 7, 6, 12, 6],
 [1, 276, 66, 126, 103, 96],
 [1, 39, 10, 19, 15, 14],
 ['Thursday', 'Sunday', 'Wednesday', 'Tuesday', 'Tuesday', 'Saturday'])

Q29

Write a Pandas program to convert year-month string to dates adding a specified day
of the month.

In [251]:
df = pd.Series(['11 Jan 2015','11 Feb 2016','11 Mar 2017','11 Apr 2018','11 May 2019'])
df = pd.to_datetime(df,format='mixed',dayfirst=False)
df

0   2015-01-11
1   2016-02-11
2   2017-03-11
3   2018-04-11
4   2019-05-11
dtype: datetime64[us]

Q30

Write a Pandas program to filter words from a given series that contain atleast two
vowels.

In [42]:
df = pd.Series(['Red','Green','Orange','Yellow','Pink','White'])
vowel_count = df.str.count(r'[aeiouAEIOU]')
df[vowel_count >=2]

1     Green
2    Orange
3    Yellow
5     White
dtype: str

Q31

Write a Pandas program to compute the Euclidean distance between two given series.
Euclidean distance
From Wikipedia,
In mathematics, the Euclidean distance or Euclidean metric is the "ordinary" straight-line
distance between two points in Euclidean space. With this distance, Euclidean space
becomes a metric space. The associated norm is called the Euclidean norm.

In [50]:
df1 = pd.Series(np.arange(1,11))
df2 = pd.Series([11,8,7,5,8,5,3,4,7,1])
np.linalg.norm(df1 - df2)

np.float64(16.73320053068151)

Q32

Write a Pandas program to find the positions of the values neighboured by smaller
values on both sides in a given series.

In [59]:
df = pd.Series([1,8,7,5,6,5,3,4,7,1])
temp = np.diff(np.sign(np.diff(df)))
result = np.where(temp == -2)[0] + 1
result

array([1, 4, 8])

Q33

Write a Pandas program to replace missing white spaces in a given string with the
least frequent character.

In [110]:
df = pd.Series(['abc def abcdef icd'])
most_frequent = pd.Series(list(df.iloc[0])).value_counts()
df.str.replace(" ",most_frequent.index[-1])

0    abcidefiabcdefiicd
dtype: str

Q34

Write a Pandas program to compute the autocorrelations of a given numeric series.
From Wikipedia:
Autocorrelation, also known as serial correlation, is the correlation of a signal with a
delayed copy of itself as a function of delay. Informally, it is the similarity between
observations as a function of the time lag between them.

In [264]:

df = pd.Series([13.207262,4.098685,-1.435534,13.626760,-2.0,5.5,8.1,-3.4,12.0,1.2,-4.5,
   15.1,6.3,-2.346193,17.873884])
a = [round(float(df.autocorr(lag=i)), 2) for i in range(1, 11)]
a

[-0.57, -0.25, 0.8, -0.76, 0.13, 0.4, -0.81, 0.69, -0.06, -0.83]

Q35

Write a Pandas program to create a TimeSeries to display all the Sundays of given
year.

In [149]:
sundays = pd.date_range(start=f'2019-01-01', end=f'2019-12-31', freq='W-SUN')
sundays

DatetimeIndex(['2019-01-06', '2019-01-13', '2019-01-20', '2019-01-27',
               '2019-02-03', '2019-02-10', '2019-02-17', '2019-02-24',
               '2019-03-03', '2019-03-10', '2019-03-17', '2019-03-24',
               '2019-03-31', '2019-04-07', '2019-04-14', '2019-04-21',
               '2019-04-28', '2019-05-05', '2019-05-12', '2019-05-19',
               '2019-05-26', '2019-06-02', '2019-06-09', '2019-06-16',
               '2019-06-23', '2019-06-30', '2019-07-07', '2019-07-14',
               '2019-07-21', '2019-07-28', '2019-08-04', '2019-08-11',
               '2019-08-18', '2019-08-25', '2019-09-01', '2019-09-08',
               '2019-09-15', '2019-09-22', '2019-09-29', '2019-10-06',
               '2019-10-13', '2019-10-20', '2019-10-27', '2019-11-03',
               '2019-11-10', '2019-11-17', '2019-11-24', '2019-12-01',
               '2019-12-08', '2019-12-15', '2019-12-22', '2019-12-29'],
              dtype='datetime64[us]', freq='W-SUN')

Q36

Write a Pandas program to convert given series into a dataframe with its index as
another column on the dataframe.

In [180]:
sr = pd.Series([0,1,2,3,4],index=['A','B','C','D','E'])
sr.reset_index()

  index  0
0     A  0
1     B  1
2     C  2
3     D  3
4     E  4

Q37

Write a Pandas program to stack two given series vertically and horizontally.

In [191]:
sr1 = pd.Series([1,2,3,4,5])
sr2 = pd.Series(['A','B','C','D','E'])
pd.concat((sr1,sr2)),pd.concat((sr1,sr2),axis=1)

(0    1
 1    2
 2    3
 3    4
 4    5
 0    A
 1    B
 2    C
 3    D
 4    E
 dtype: object,
    0  1
 0  1  A
 1  2  B
 2  3  C
 3  4  D
 4  5  E)

Q38

Write a Pandas program to check the equality of two given series.

In [193]:
sr1 = pd.Series([1,8,9,6,4,6,2])
sr2 = pd.Series([1,0,9,6,4,6,2])
sr1 == sr2

0     True
1    False
2     True
3     True
4     True
5     True
6     True
dtype: bool

Q39

Write a Pandas program to find the index of the first occurrence of the smallest and
largest value of a given series.

In [215]:
sr1 = pd.Series([1,8,9,6,4,6,2])
sr1.idxmin(),sr1.idxmax()

(0, 2)

Q40

Write a Pandas program to check inequality over the index axis of a given dataframe
and a given series.

In [212]:
df = pd.DataFrame({
  
 'W':[68.0 ,75.0 ,86.0 ,80.0,None],
 'X':[78 ,75.0 ,None ,80.0,86.0],
 'Y':[84, 94, 89, 86,86],
 'Z':[86 ,97 ,96 ,72,83],
 })
sr1 = pd.Series([68.0,75.0,86.0,80.0,None])

df.ne(sr1,axis=0)

       W      X     Y     Z
0  False   True  True  True
1  False  False  True  True
2  False   True  True  True
3  False  False  True  True
4   True   True  True  True