In [1]:
# ANOVA : HO: Partent's education level has no impact on the child's math score

In [55]:
from scipy.stats import f_oneway
import pandas as pd

In [56]:
df = pd.read_csv('StudentsPerformance.csv')
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [57]:
g1 = df['math score'][df['parental level of education'] == 'some high school']
g2 = df['math score'][df['parental level of education'] == 'high school']
g3 = df['math score'][df['parental level of education'] == 'some college']
g4 = df['math score'][df['parental level of education'] == 'associate\'s degree']
g5 = df['math score'][df['parental level of education'] == 'bachelor\'s degree']
g6 = df['math score'][df['parental level of education'] == 'master\'s degree']

In [58]:
fstat, pval = f_oneway(g1,g2,g3,g4,g5,g6)
alpha = 0.05

if pval < alpha :
    print('Reject HO')
else :
    print('Does Not Reject HO')

Reject HO

In [59]:
print("g1 size:", len(g1))
print("g2 size:", len(g2))
print("g3 size:", len(g3))
print("g4 size:", len(g4))
print("g5 size:", len(g5))
print("g6 size:", len(g6))

g1 size: 179
g2 size: 196
g3 size: 226
g4 size: 222
g5 size: 118
g6 size: 59

# Excercise

Excercise : Is there a statistically significant difference between how people tip, whose bill amounts are < $13, $13-17,$17-22,>$22 in the tips dataset? (Handle Boundry Condition Appropriately)

In [60]:
df = pd.read_csv(r"C:\Users\PGCP-AI.STUDENTSDC\Downloads\tips.csv")
df.head()

,total_bill,tip,gender,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3.560330e+15,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4.478070e+15,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6.011810e+15,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4.676140e+15,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4.832730e+15,Sun2251

In [61]:
g1 = df['tip'][df['total_bill'] < 13]
g2 = df['tip'][df['total_bill'].between(13,17,inclusive='left')]
g3 = df['tip'][df['total_bill'].between(17,22,inclusive='left')]
g4 = df['tip'][df['total_bill'] >= 22]

In [62]:
fstat, pval = f_oneway(g1,g2,g3,g4)

print('F-Statistic :',fstat)
print('P-Value :',pval)

alpha = 0.05

if pval < alpha :
    print('Reject HO')
else :
    print('Does Not Reject HO')

F-Statistic : 47.468466815824726
P-Value : 4.021249116944337e-24
Reject HO

In [63]:
print("g1 size:", len(g1))
print("g2 size:", len(g2))
print("g3 size:", len(g3))
print("g4 size:", len(g4))

g1 size: 54
g2 size: 59
g3 size: 54
g4 size: 77