In [1]:
# Chi-Square test of independence
# HO : There is NO Statistically significant dependence between Cancelled/Pending orders and Order Fulfilment.

In [3]:
from scipy.stats import chi2_contingency
import pandas as pd

In [14]:
df = pd.read_csv(r"C:\Users\PGCP-AI.STUDENTSDC\Downloads\Amazon Sale Report.csv",low_memory=False,index_col=0)
df.head()

,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,Size,...,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by,Unnamed: 22
index,,,,,,,,,,,,,,,,,,,,,
0,405-8078784-5731545,04-30-22,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,S,...,INR,647.62,MUMBAI,MAHARASHTRA,400081.0,IN,NaN,False,Easy Ship,NaN
1,171-9198151-1101146,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3781,JNE3781-KR-XXXL,kurta,3XL,...,INR,406.00,BENGALURU,KARNATAKA,560085.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,NaN
2,404-0687676-7273146,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3371,JNE3371-KR-XL,kurta,XL,...,INR,329.00,NAVI MUMBAI,MAHARASHTRA,410210.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,True,NaN,NaN
3,403-9615377-8133951,04-30-22,Cancelled,Merchant,Amazon.in,Standard,J0341,J0341-DR-L,Western Dress,L,...,INR,753.33,PUDUCHERRY,PUDUCHERRY,605008.0,IN,NaN,False,Easy Ship,NaN
4,407-1069790-7240320,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,3XL,...,INR,574.00,CHENNAI,TAMIL NADU,600073.0,IN,NaN,False,NaN,NaN

In [15]:
cancelled_pending_orders = df[df['Status'].isin(['Cancelled','Pending'])]

In [26]:
# Create a Contingency table
contingency_table = pd.crosstab(cancelled_pending_orders['Status'],cancelled_pending_orders['Fulfilment'])
contingency_table

Fulfilment  Amazon  Merchant
Status
Cancelled    11471      6861
Pending        415       243

In [17]:
# Perofrm chi-square test
chi2,p,dof,ex = chi2_contingency(contingency_table)
print('Chi-Squared Statistic :',chi2)
print('P-Value :',p)
print('Degrees of Freedom :',dof)
print('Expected Values :',ex)

Chi-Squared Statistic : 0.04729799287402296
P-Value : 0.8278334990054204
Degrees of Freedom : 1
Expected Values : [[11474.15229068  6857.84770932]
 [  411.84770932   246.15229068]]

In [18]:
if p < 0.05 :
    print('Reject Null Hypothesis.')
else :
    print('Fail to Reject Null Hypothesis.')

Fail to Reject Null Hypothesis.

# Excercise

Excercise : \
(a) Were gender and survival independent in titanic?\
(b) Were Passanger class and survival related in titanic?

In [19]:
import seaborn as sns

df = sns.load_dataset('titanic')
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [23]:
genders = df[df['sex'].isin(['male','female'])]

In [24]:
contingency_table = pd.crosstab(genders['sex'],genders['survived'])
contingency_table

survived    0    1
sex
female     81  233
male      468  109

In [25]:
# Perofrm chi-square test
chi2,p,dof,ex = chi2_contingency(contingency_table)
print('Chi-Squared Statistic :',chi2)
print('P-Value :',p)
print('Degrees of Freedom :',dof)
print('Expected Values :',ex)

Chi-Squared Statistic : 260.71702016732104
P-Value : 1.1973570627755645e-58
Degrees of Freedom : 1
Expected Values : [[193.47474747 120.52525253]
 [355.52525253 221.47474747]]

In [27]:
if p < 0.05 :
    print('Reject Null Hypothesis.')
else :
    print('Fail to Reject Null Hypothesis.')

Reject Null Hypothesis.