In [12]:
import pandas as pd
from scipy import stats
import seaborn as sns

In [13]:
df = pd.read_csv(r"C:\Users\PGCP-AI.STUDENTSDC\Desktop\Data_Analytics\DA_Pandas\tips.csv")
df.head()

,total_bill,tip,gender,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3.560330e+15,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4.478070e+15,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6.011810e+15,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4.676140e+15,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4.832730e+15,Sun2251

In [14]:
male_tips = df[df['gender'] == 'Male']['tip']
female_tips = df[df['gender'] == 'Female']['tip']

In [15]:
male_tips = male_tips.sample(n=30,replace=False)
female_tips = female_tips.sample(n=30,replace=False)

print('Male mean tip :',male_tips.mean())
print('Female mean tip :',female_tips.mean())

Male mean tip : 3.156
Female mean tip : 2.629

In [16]:
# perform two_sample t-test
t_statistic, p_value = stats.ttest_ind(male_tips, female_tips)

In [17]:
# Significance level (alpha)
alpha = 0.05
print('T-Statistic :',t_statistic)
print('P-Value :',p_value)

T-Statistic : 1.8476482209394938
P-Value : 0.06975489037721974

In [18]:
if p_value < alpha :
    print('There is a significant fifference in spending score between Male and Female groups.')
else:
    print('There is a no significant fifference in spending score between Male and Female groups.')

There is a no significant fifference in spending score between Male and Female groups.

# Excercise

Excercise : Is there a statistically significant difference in the average runs scored by Sachin Tendulkar when playing against Australia versus Pakistan ? (sachin_tendulkar.csv)

In [19]:
df = pd.read_csv('sachin_tendulkar.csv')
df.head()

,Match_No,Innings,match_date,Versus,mode_of_dismissal,Runs,Balls_faced
0,1,1,1989-12-18 00:00:00,Pakistan,c Wasim Akram b Waqar Younis,0,2
1,2,2,1990-03-01 00:00:00,New Zealand,c & b S A Thomson,0,2
2,3,3,1990-03-06 00:00:00,New Zealand,c †I D S Smith b S A Thomson,36,39
3,4,4,1990-04-25 00:00:00,Sri Lanka,run out,10,12
4,5,5,1990-04-27 00:00:00,Pakistan,c Saeed Anwar b Imran Khan,20,25

In [20]:
vs_aus = df[df['Versus'] == 'Australia']['Runs']
vs_pak = df[df['Versus'] == 'Pakistan']['Runs']

In [21]:
vs_aus = vs_aus.sample(n=30,replace=False)
vs_pak = vs_pak.sample(n=30,replace=False)

print('Vs Australia Mean Runs :',vs_aus.mean())
print('Vs Pakistan Mean Runs :',vs_pak.mean())

Vs Australia Mean Runs : 45.63333333333333
Vs Pakistan Mean Runs : 35.56666666666667

In [24]:
result = stats.ttest_ind(vs_aus,vs_pak)
print('T-Statistic :',result.statistic)
print('P-Value :',result.pvalue)

T-Statistic : 0.9506042987294958
P-Value : 0.3457498348302505

In [26]:
alpha = 0.05
if p_value < alpha :
    print('There is a Significant Difference in Mean Runs score by Sacin Tendulkar Versus Australia and Pakistan.')
else:
    print('There is a No Significant Difference in Mean Runs score by Sacin Tendulkar Versus Australia and Pakistan.')

There is a No Significant Difference in Mean Runs score by Sacin Tendulkar Versus Australia and Pakistan.