In [1]:
#1-sample T-test: is average population tip = $3?
#HO: meu = average tip=$3
import pandas as pd
from scipy import stats
import seaborn as sns

In [21]:
df = pd.read_csv(r"C:\Users\PGCP-AI.STUDENTSDC\Desktop\Data_Analytics\DA_Pandas\tips.csv")
df.head()

,total_bill,tip,gender,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3.560330e+15,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4.478070e+15,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6.011810e+15,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4.676140e+15,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4.832730e+15,Sun2251

In [22]:
our_column = df['tip']
our_column = our_column.sample(n=30,replace=False)

# Two-Tailed t_test

In [23]:
meu = 3 #meu

In [24]:
#perform one sample T-test
t_statistics, p_value = stats.ttest_1samp(our_column, meu)

In [25]:
#automatically retuens 2-tailed p-value
print('p-value:', p_value)

p-value: 0.4222009942383707

In [26]:
alpha = 0.05
if p_value < alpha:
    print('Reject HO')
else :
    print('Failed To Reject Ho')

Failed To Reject Ho

In [27]:
our_column.mean()

np.float64(2.842333333333334)

# One-Tailed t_test

In [28]:
# Perform one-sample right tailed test
# HO : mu <= 3
# Ha : mu > 3

result = stats.ttest_1samp(our_column, meu, alternative = 'greater') # Greater means HO: <= and alternate : >

In [29]:
print('T-Statistic :',result.statistic)
print('P-Value (One-Tailed) :',result.pvalue)

T-Statistic : -0.8141380485285096
P-Value (One-Tailed) : 0.7888995028808147

In [30]:
alpha = 0.05
if result.pvalue < alpha :
    print('Reject Ho (mean is significatly grater than ',meu,')')
else:
    print('Do not reject HO')

Do not reject HO

# Excercise

Excercise : Use loan dataset. Run two-tailed and one-tailed one sample t-test\
Two-tailed -> HO : Average income = 50, H1 : Average income <> 50.\
One-tailed -> HO : Average income >= 50, H1 : Average income < 50.

In [31]:
df = pd.read_csv('loan.csv')
df.head()

   age  ed  employ  address  income  debtinc   creddebt   othdebt  default
0   41   3      17       12     176      9.3  11.359392  5.008608      1.0
1   27   1      10        6      31     17.3   1.362202  4.000798      0.0
2   40   1      15       14      55      5.5   0.856075  2.168925      0.0
3   41   1      15       14     120      2.9   2.658720  0.821280      0.0
4   24   2       2        0      28     17.3   1.787436  3.056564      1.0

In [32]:
our_column = df['income']
our_column = our_column.sample(n=30,replace=False)

In [33]:
# Two Tailed
meu = 50
result = stats.ttest_1samp(our_column, meu)
print('T-Statistic :',result.statistic)
print('P-Value (Two-Tailed) :',result.pvalue)

T-Statistic : -1.1996691024340784
P-Value (Two-Tailed) : 0.23997768120664204

In [34]:
alpha = 0.05
if result.pvalue < alpha :
    print('Reject Ho')
else:
    print('Do not reject HO')

Do not reject HO

In [35]:
# Two Tailed
result = stats.ttest_1samp(our_column, meu, alternative = 'less')
print('T-Statistic :',result.statistic)
print('P-Value (Two-Tailed) :',result.pvalue)

T-Statistic : -1.1996691024340784
P-Value (Two-Tailed) : 0.11998884060332102

In [36]:
alpha = 0.05
if result.pvalue < alpha :
    print('Reject Ho ( mean is significatly less than ',meu,')')
else:
    print('Do not reject HO')

Do not reject HO

In [37]:
our_column.mean()

np.float64(44.0)