In [1]:
# Paired t_test : A company has launched some offer
# HO : Pre and post usage is the same (i.e offer is not effective)

In [5]:
from scipy.stats import ttest_rel
import pandas as pd

In [7]:
df = pd.read_csv('cust_seg.csv')
df.head()

,custid,sex,AqChannel,region,Marital_status,segment,pre_usage,Post_usage_1month,Latest_mon_usage,post_usage_2ndmonth
0,70,0,4,1,1,1,57,52,49.2,57.2
1,121,1,4,2,1,3,68,59,63.6,64.9
2,86,0,4,3,1,1,44,33,64.8,36.3
3,141,0,4,3,1,3,63,44,56.4,48.4
4,172,0,4,2,1,2,47,52,68.4,57.2

In [8]:
usage_data = df[['pre_usage','Post_usage_1month']]
usage_data = usage_data.sample(n=30)

In [9]:
tstat, pval = ttest_rel(usage_data['pre_usage'],usage_data['Post_usage_1month'])

alpha = 0.05
if pval < alpha :
    print('Reject null hypothesis')
else :
    print('Fail top reject null hypothesis')

Fail top reject null hypothesis

# Excercise

Excercise : On the Hypothermia dataset , check whether the urgent treatment is effective (consider column t.1 and t.2)

In [11]:
df = pd.read_csv('Hypothermia.csv')
df.head()

,case,code,date,time,weight,t.nur,t.or,t.1,t.2,t.3,t.4,t.5,t.6
0,1,98887,12.0,20.30,2550,29,28,34.0,35.1,,,,
1,2,98528,11.0,18.10,1200,29,23,29.0,33.0,36.5,36.8,,
2,3,95723,3.0,10.24,2650,31,32,31.0,36.8,,,,
3,4,97694,8.0,0.30,800,27,22,32.0,34.0,35,35.5,36,36.5
4,5,96892,6.0,6.20,1880,30,30,32.2,36.6,,,,

In [15]:
use_data = df[['t.1','t.2']]
use_data = use_data.sample(n=30)

In [17]:
print('Use Data Mean :',use_data.mean())

Use Data Mean : t.1    35.34
t.2    36.49
dtype: float64

In [16]:
tstat, pval = ttest_rel(use_data['t.1'],use_data['t.2'])

alpha = 0.05
if pval < alpha :
    print('Reject null hypothesis')
else :
    print('Fail top reject null hypothesis')

Reject null hypothesis