In [1]:
import pandas as pd

In [32]:
df = pd.read_csv(r"C:\Users\PGCP-AI.STUDENTSDC\Downloads\titanic.csv")
df.head()

   survived  pclass  gender   age  sibsp  parch     fare embarked deck
0         0       3    male  22.0      1      0   7.2500        S  NaN
1         1       1  female  38.0      1      0  71.2833        C    C
2         1       3  female  26.0      0      0   7.9250        S  NaN
3         1       1  female  35.0      1      0  53.1000        S    C
4         0       3    male  35.0      0      0   8.0500        S  NaN

In [31]:
df = df[['gender','survived']]
df.head()

   gender  survived
0    male         0
1  female         1
2  female         1
3  female         1
4    male         0

In [30]:
total = len(df)
total_male = len(df[df['gender'] == 'male'])
total_female = len(df[df.gender == 'female'])
print(total_male)
print(total_female)

577
314

In [21]:
p_female = total_female / total
print(p_female)
p_male = total_male / total
print(p_male)

0.35241301907968575
0.6475869809203143

In [22]:
# Marginal Probability of survival
total_survived = len(df[df.survived == 1])
print(total_survived)
total_not_survived = len(df[df.survived == 0])
print(total_not_survived)

342
549

In [23]:
p_survived = total_survived / total
p_not_survived = total_not_survived / total

In [28]:
print('\nMargin Probability')
print(f'P(Survived=1) :{p_survived:.3f}')
print(f'P(survived=0):{p_not_survived:.3f}')
print(f'P(female):{p_female:.3f}')
print(f'P(male):{p_male:.3f}')

Margin Probability
P(Survived=1) :0.384
P(survived=0):0.616
P(female):0.352
P(male):0.648

In [26]:
# Joint Probability
p_female_survived = len(df[(df.gender == 'female') & (df.survived == 1)]) / total
p_female_not_survived = len(df[(df.gender == 'female') & (df.survived == 0)]) / total
p_male_survived = len(df[(df.gender == 'male') & (df.survived == 1)]) / total
p_male_not_survived = len(df[(df.gender == 'male') & (df.survived == 0)]) / total

print('\nJoint Probability')
print(f'P(female,Survived=1) : {p_female_survived:.3f}')
print(f'P(female,Survived=0) : {p_female_not_survived:.3f}')
print(f'P(male,Survived=1) : {p_male_survived:.3f}')
print(f'P(male,Survived=0) : {p_male_not_survived:.3f}')

Joint Probability
P(female,Survived=1) : 0.262
P(female,Survived=0) : 0.091
P(male,Survived=1) : 0.122
P(male,Survived=0) : 0.525

In [27]:
print('\nConditional Probability')
p_survived_given_female = p_female_survived / p_female
print(f'P(Survived=1 | gender=female):{p_survived_given_female:.3f}')
p_survived_given_male = p_male_survived / p_male
print(f'P(Survived=1 | gender=male):{p_survived_given_male:.3f}')

Conditional Probability
P(Survived=1 | gender=female):0.742
P(Survived=1 | gender=male):0.189